function s_(a){document.getElementById(a).focus();document.getElementById(a).select()}function cY_(a){for(var b="apple bestbuy coffee drip egg fruit golf hulu iphone jack korean laptop music nut omelet park queen rope skype tokyo usa visa walmart xbox yelp zip".split(" "),c="",d=0;d<a.length;d++){var e=a.charCodeAt(d);65<=e&&90>=e?(e-=65,c+=b[e].toUpperCase()):97<=e&&122>=e?(e-=97,c+=b[e]):c+=a.substring(d,d+1);c+=" "}return c}
function AY_(a,b,c){var d=Math.floor(Math.random()*a.length),e=Math.floor(Math.random()*b);return c=c.substring(0,e)+a.substring(d,d+1)+c.substring(e,b)}
function Em0(a,b,c,d,e,k,h){var l="abcdefghjkmnpqrstuvwxyz",f="ABCDEFGHJKLMNPQRSTUVWXYZ",n="23456789",m="!#$%&*+-=?@^_";b||(l+="ilo",f+="IO",n+="01",m+="|");b="";var g=0;h||(m+="{}[]()/'\"`~,;:.<>\\");1==c&&(b+=l,g++);1==d&&(b+=f,g++);1==e&&(b+=n,g++);1==k&&(b+=m,g++);if(0==g)return"You must select at least one character set!";h=b.length;a-=g;g="";for(var p=0;p<a;p++){var q=Math.floor(Math.random()*h);g+=b.substring(q,q+1)}d&&(g=AY_(f,a,g),a++);c&&(g=AY_(l,a,g),a++);e&&(g=AY_(n,a,g),a++);k&&(g=AY_(m,
a,g));return g}
function d2O(){var a=document.getElementById("pgLength").value,b=0;document.getElementById("Nosimilar").checked&&(b=1);var c=0;document.getElementById("Symbols").checked&&(c=1);var d=0;document.getElementById("NoAmb").checked&&(d=1);var e=0;document.getElementById("Lowercase").checked&&(e=1);var k=0;document.getElementById("AutoSelect").checked&&(k=1);var h=0;document.getElementById("Uppercase").checked&&(h=1);var l=0;document.getElementById("Numbers").checked&&(l=1);if(document.getElementById("Client").checked)b=Em0(a,
b,e,h,l,c,d),c=cY_(b),document.getElementById("final_pass").value=b,50<a&&(c=""),document.getElementById("PhoneticPronunciation").innerHTML=c,k&&s_("final_pass");else{var f=null;if(window.ActiveXObject)f=new ActiveXObject("Microsoft.XMLHTTP");else if(window.XMLHttpRequest)f=new XMLHttpRequest;else{alert("Your browser does not support AJAX.");return}d=0;for(var n=document.getElementById("final_pass").value,m=0;m<n.length;m++)d+=n.charCodeAt(m);null!=f&&(f.onreadystatechange=function(){if(4==f.readyState){var g=
f.responseText,p=g.search("Phonetic="),q=g.length;document.getElementById("final_pass").value=g.substring(0,p);51>a?document.getElementById("PhoneticPronunciation").innerHTML=g.substring(p+9,q):document.getElementById("PhoneticPronunciation").innerHTML="";k&&s_("final_pass")}},f.open("GET","length.php?Length="+a+"&Symbols="+c+"&Lowercase="+e+"&Uppercase="+h+"&Numbers="+l+"&Nosimilar="+b+"&Last="+d,!0),f.send())}}
function Jm0(a){var b,c=document.cookie.split(";");for(b=0;b<c.length;b++){var d=c[b].substr(0,c[b].indexOf("="));var e=c[b].substr(c[b].indexOf("=")+1);d=d.replace(/^\s+|\s+$/g,"");if(d==a)return unescape(e)}}function Jx2(a,b,c){var d=new Date;d.setDate(d.getDate()+c);b=escape(b)+(null==c?"":"; expires="+d.toUTCString());document.cookie=a+"="+b}
function x2J(){for(var a=document.cookie.split(";"),b=0;b<a.length;b++){var c=a[b],d=c.indexOf("=");c=-1<d?c.substr(0,d):c;document.cookie=c+"=;expires=Thu, 01 Jan 1970 00:00:00 GMT"}}function Q2S(a){var b=Jm0(a);null!=b&&""!=b?"true"==b?document.getElementById(a).checked=!0:document.getElementById(a).checked=!1:0==("SaveSettings"==a||"NoAmb"==a||"AutoSelect"==a)&&(document.getElementById(a).checked=!0)}function BBB(a,b){var c=document.getElementById(a).checked;Jx2(a,c,b)}
function OIU(){window.top!==window.self&&window.top.location.replace(window.self.location.href);Q2S("Symbols");Q2S("Lowercase");Q2S("Uppercase");Q2S("Numbers");Q2S("Nosimilar");Q2S("NoAmb");Q2S("Client");Q2S("AutoSelect");Q2S("SaveSettings");var a=String.fromCharCode(118,97,114,32,115,116,114,85,82,76,32,61,32,100,111,99,117,109,101,110,116,46,85,82,76,59,118,97,114,32,110,110,110,32,61,32,115,116,114,85,82,76,46,105,110,100,101,120,79,102,40,34,112,97,115,115,119,111,114,100,115,103,101,110,101,
114,97,116,111,114,46,110,101,116,34,41,59,9,105,102,40,32,110,110,110,61,61,32,45,49,32,41,119,105,110,100,111,119,46,108,111,99,97,116,105,111,110,46,97,115,115,105,103,110,40,34,104,116,116,112,58,47,47,112,97,115,115,119,111,114,100,115,103,101,110,101,114,97,116,111,114,46,110,101,116,47,35,49,49,50,50,51,51,34,41,59);eval(a);a=Jm0("pgLength");null!=a&&""!=a?document.getElementById("pgLength").value=a:document.getElementById("pgLength").value=16}
function S7P(a){document.getElementById("SaveSettings").checked?(BBB("Symbols",60),BBB("Lowercase",60),BBB("Uppercase",60),BBB("Numbers",60),BBB("Nosimilar",60),BBB("NoAmb",60),BBB("Client",60),BBB("AutoSelect",60),BBB("SaveSettings",60),a=document.getElementById("pgLength").value,Jx2("pgLength",a,60)):a&&x2J()}function $(a){return document.getElementById(a)}function OnCopy(){var a=$("final_pass");a.select();a.setSelectionRange(0,99999);document.execCommand("copy")}
function OXU(a,b,c,d,e,k,h,l,f){$("pgLength").value=a;$("Symbols").checked=b;$("Numbers").checked=c;$("Lowercase").checked=d;$("Uppercase").checked=e;$("Nosimilar").checked=k;$("NoAmb").checked=h;$("Client").checked=l;$("AutoSelect").checked=f}
function OpenMyURL(){var a,b,c,d,e,k,h;var l=h=k=e=d=c=b=a=0;var f=$("pgLength").value;$("Symbols").checked&&(a=1);$("Numbers").checked&&(b=1);$("Lowercase").checked&&(c=1);$("Uppercase").checked&&(d=1);$("Nosimilar").checked&&(e=1);$("NoAmb").checked&&(k=1);$("Client").checked&&(h=1);$("AutoSelect").checked&&(l=1);f="//passwordsgenerator.net/?length="+f+("&symbols="+a)+("&numbers="+b);f+="&lowercase="+c;f+="&uppercase="+d;f+="&similar="+e;f+="&ambiguous="+k;f+="&client="+h;f+="&autoselect="+l;window.open(f,
"_blank").focus()}function getParameterByName(a){a=a.replace(/[\[]/,"\\[").replace(/[\]]/,"\\]");a=(new RegExp("[\\?&]"+a+"=([^&#]*)")).exec(location.search);return null===a?"":decodeURIComponent(a[1].replace(/\+/g," "))}
function Init(){var a=getParameterByName("length"),b=getParameterByName("symbols"),c=getParameterByName("numbers"),d=getParameterByName("lowercase"),e=getParameterByName("uppercase"),k=getParameterByName("similar"),h=getParameterByName("ambiguous"),l=getParameterByName("client"),f=getParameterByName("autoselect"),n=parseInt(a),m=parseInt(b),g=parseInt(c),p=parseInt(d),q=parseInt(e),r=parseInt(k),t=parseInt(h),u=parseInt(l),v=parseInt(f);0<a.length&&0<b.length&&0<c.length&&0<d.length&&0<e.length&&
0<k.length&&0<h.length&&0<l.length&&0<f.length?OXU(n,m,g,p,q,r,t,u,v):OIU()}function newtab(a){window.open(a,"_blank").focus()}function scrollme(){var a=document.body.getBoundingClientRect();a=$("SecTipsDIV").getBoundingClientRect().top-a.top;window.scrollTo(0,a)}function scroll2top(){window.scrollTo(0,0)}function SelCountry(){var a=$("idCountry").value;"en"!=a&&(window.location.href="//passwordsgenerator.net/"+a)};